In [ ]:
!pip install -q pyomo

In [ ]:
from pyomo.environ import * 

In [ ]:
import numpy as np

1.ANSWER:\
The Mathematical model of the Trasportation problem is given as:\
Let $C_{wm}$ be the cost of transporting one truck-load of ACUs and $x_{wm}$ be the number of transporting trucks from Warehouse $\textbf{w}$ to Market $\textbf{m}$ respectively.Then our optimization problem is :


$\textbf{Minimize:}$
\begin{align}
\sum_{w}\sum_{m} C_{wm} x_{wm}
\end{align}

$\textbf{Subject to:}$
\begin{align}
\sum_{m} x_{wm} &\leq \text{Avail. Stock at Warehouse w}&&\forall\text{  w }\\
\sum_{w} x_{wm} &= \text{Demand at Market m}&&\forall\text{   m }
\end{align}

$\text{where decision variables}\text{  }\  x_{wm} \text{ are non-negative integers .}$



In [ ]:
import pandas as pd

In [ ]:
data_csvfile = pd.read_csv('lab5_ex1.csv')

In [ ]:
data_csvfile.index

RangeIndex(start=0, stop=9, step=1)

In [ ]:
print('num rows:', len(data_csvfile.index))

num rows: 9


In [ ]:
print(data_csvfile.iloc[0,:])

Warehouse       Ahmedabad
Indore                427
Jodhpur               617
Vellore              1270
Kanpur                982
Hyderabad             915
Patna                 943
Raipur                974
Cuttack              1265
Avail. Stock          100
Name: 0, dtype: object


In [ ]:
print(data_csvfile.iloc[1,:])

Warehouse       Bengaluru
Indore               1179
Jodhpur              1623
Vellore               372
Kanpur               2072
Hyderabad             257
Patna                1373
Raipur               1052
Cuttack               959
Avail. Stock          250
Name: 1, dtype: object


In [ ]:
print(data_csvfile.iloc[2,:])

Warehouse       Chennai
Indore             1409
Jodhpur            1823
Vellore              59
Kanpur             2127
Hyderabad           358
Patna              1422
Raipur             1304
Cuttack             811
Avail. Stock        200
Name: 2, dtype: object


In [ ]:
print(data_csvfile.iloc[3,:])

Warehouse       Delhi
Indore           1123
Jodhpur           533
Vellore          2265
Kanpur            467
Hyderabad        1896
Patna             941
Raipur           1232
Cuttack          1348
Avail. Stock      200
Name: 3, dtype: object


In [ ]:
print(data_csvfile.iloc[4,:])

Warehouse       kolkata
Indore             1712
Jodhpur            2079
Vellore            1830
Kanpur             1499
Hyderabad          1929
Patna               439
Raipur              691
Cuttack             128
Avail. Stock        150
Name: 4, dtype: object


In [ ]:
print(data_csvfile.iloc[5,:])

Warehouse       lucknow
Indore              886
Jodhpur             760
Vellore            1965
Kanpur               83
Hyderabad          1759
Patna               395
Raipur              795
Cuttack            1332
Avail. Stock         90
Name: 5, dtype: object


In [ ]:
print(data_csvfile.iloc[6,:])

Warehouse       Mumbai
Indore             546
Jodhpur            817
Vellore           1045
Kanpur            1232
Hyderabad          905
Patna             1211
Raipur            1187
Cuttack           1487
Avail. Stock       290
Name: 6, dtype: object


In [ ]:
print(data_csvfile.iloc[7,:])

Warehouse       Nagpur
Indore             495
Jodhpur           1062
Vellore           1113
Kanpur            1121
Hyderabad          802
Patna             1125
Raipur             474
Cuttack            801
Avail. Stock       200
Name: 7, dtype: object


In [ ]:
data_csvfile.columns

Index(['Warehouse', 'Indore', 'Jodhpur', 'Vellore', 'Kanpur', 'Hyderabad',
       'Patna', 'Raipur', 'Cuttack', 'Avail. Stock'],
      dtype='object')

In [ ]:
print('num  columns: ',len(data_csvfile.columns))

num  columns:  10


In [ ]:
print(data_csvfile.iloc[:,1])

0     427
1    1179
2    1409
3    1123
4    1712
5     886
6     546
7     495
8      75
Name: Indore, dtype: int64


In [ ]:
print(data_csvfile.iloc[:,2])

0     617
1    1623
2    1823
3     533
4    2079
5     760
6     817
7    1062
8     300
Name: Jodhpur, dtype: int64


In [ ]:
print(data_csvfile.iloc[:,3])

0    1270
1     372
2      59
3    2265
4    1830
5    1965
6    1045
7    1113
8     250
Name: Vellore, dtype: int64


In [ ]:
print(data_csvfile.iloc[:,4])

0     982
1    2072
2    2127
3     467
4    1499
5      83
6    1232
7    1121
8     200
Name: Kanpur, dtype: int64


In [ ]:
print(data_csvfile.iloc[:,5])

0     915
1     257
2     358
3    1896
4    1929
5    1759
6     905
7     802
8     400
Name: Hyderabad, dtype: int64


In [ ]:
print(data_csvfile.iloc[:,6])

0     943
1    1373
2    1422
3     941
4     439
5     395
6    1211
7    1125
8     100
Name: Patna, dtype: int64


In [ ]:
print(data_csvfile.iloc[:,7])

0     974
1    1052
2    1304
3    1232
4     691
5     795
6    1187
7     474
8      50
Name: Raipur, dtype: int64


In [ ]:
print(data_csvfile.iloc[:,8])

0    1265
1     959
2     811
3    1348
4     128
5    1332
6    1487
7     801
8      70
Name: Cuttack, dtype: int64


In [ ]:
model = ConcreteModel()

In [ ]:
M = len(data_csvfile.index)-1 #we declare a Python variable M denoting the number of Warehouses
print('num warehouse: ',M)

num warehouse:  8


In [ ]:
N = len(data_csvfile.columns)-2 #we declare a Python variable N denoting the number of Markets
print('num markets: ',N)

num markets:  8


In [ ]:
row_indices = range(M)
col_indices = range(N)

print(row_indices)
print(col_indices)

range(0, 8)
range(0, 8)


In [ ]:
# the contents of costs
for row_idx in row_indices:
  for col_idx in col_indices:
    print('cost[',row_idx,'][',col_idx+1,']:',data_csvfile.iloc[row_idx, col_idx+1])

cost[ 0 ][ 1 ]: 427
cost[ 0 ][ 2 ]: 617
cost[ 0 ][ 3 ]: 1270
cost[ 0 ][ 4 ]: 982
cost[ 0 ][ 5 ]: 915
cost[ 0 ][ 6 ]: 943
cost[ 0 ][ 7 ]: 974
cost[ 0 ][ 8 ]: 1265
cost[ 1 ][ 1 ]: 1179
cost[ 1 ][ 2 ]: 1623
cost[ 1 ][ 3 ]: 372
cost[ 1 ][ 4 ]: 2072
cost[ 1 ][ 5 ]: 257
cost[ 1 ][ 6 ]: 1373
cost[ 1 ][ 7 ]: 1052
cost[ 1 ][ 8 ]: 959
cost[ 2 ][ 1 ]: 1409
cost[ 2 ][ 2 ]: 1823
cost[ 2 ][ 3 ]: 59
cost[ 2 ][ 4 ]: 2127
cost[ 2 ][ 5 ]: 358
cost[ 2 ][ 6 ]: 1422
cost[ 2 ][ 7 ]: 1304
cost[ 2 ][ 8 ]: 811
cost[ 3 ][ 1 ]: 1123
cost[ 3 ][ 2 ]: 533
cost[ 3 ][ 3 ]: 2265
cost[ 3 ][ 4 ]: 467
cost[ 3 ][ 5 ]: 1896
cost[ 3 ][ 6 ]: 941
cost[ 3 ][ 7 ]: 1232
cost[ 3 ][ 8 ]: 1348
cost[ 4 ][ 1 ]: 1712
cost[ 4 ][ 2 ]: 2079
cost[ 4 ][ 3 ]: 1830
cost[ 4 ][ 4 ]: 1499
cost[ 4 ][ 5 ]: 1929
cost[ 4 ][ 6 ]: 439
cost[ 4 ][ 7 ]: 691
cost[ 4 ][ 8 ]: 128
cost[ 5 ][ 1 ]: 886
cost[ 5 ][ 2 ]: 760
cost[ 5 ][ 3 ]: 1965
cost[ 5 ][ 4 ]: 83
cost[ 5 ][ 5 ]: 1759
cost[ 5 ][ 6 ]: 395
cost[ 5 ][ 7 ]: 795
cost[ 5 ][ 8 ]: 1332
cost[ 6 ][ 1 ]: 5

In [ ]:
model.x = Var(row_indices, col_indices, domain= NonNegativeIntegers)

In [ ]:
model.objective = Objective(expr=sum(data_csvfile.iloc[i,j+1]*model.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

In [ ]:
model.constraints = ConstraintList()

In [ ]:
#to get the Available-stock limit at different markets from the file we can use the following
print(data_csvfile.iloc[:8,N+1])

0    100.0
1    250.0
2    200.0
3    200.0
4    150.0
5     90.0
6    290.0
7    200.0
Name: Avail. Stock, dtype: float64


In [ ]:
#the Available-stock limit constraints
model.constraints.add(expr=sum(model.x[0,j] for j in col_indices) <= data_csvfile.iloc[0,N+1]) 
model.constraints.add(expr=sum(model.x[1,j] for j in col_indices) <= data_csvfile.iloc[1,N+1])
model.constraints.add(expr=sum(model.x[2,j] for j in col_indices) <= data_csvfile.iloc[2,N+1]) 
model.constraints.add(expr=sum(model.x[3,j] for j in col_indices) <= data_csvfile.iloc[3,N+1])
model.constraints.add(expr=sum(model.x[4,j] for j in col_indices) <= data_csvfile.iloc[4,N+1])
model.constraints.add(expr=sum(model.x[5,j] for j in col_indices) <= data_csvfile.iloc[5,N+1])
model.constraints.add(expr=sum(model.x[6,j] for j in col_indices) <= data_csvfile.iloc[6,N+1])
model.constraints.add(expr=sum(model.x[7,j] for j in col_indices) <= data_csvfile.iloc[7,N+1])

In [ ]:
#the demand constraints
model.constraints.add(expr=sum(model.x[i,0] for i in row_indices) == data_csvfile.iloc[M,1])
model.constraints.add(expr=sum(model.x[i,1] for i in row_indices) == data_csvfile.iloc[M,2])
model.constraints.add(expr=sum(model.x[i,2] for i in row_indices) == data_csvfile.iloc[M,3])
model.constraints.add(expr=sum(model.x[i,3] for i in row_indices) == data_csvfile.iloc[M,4])
model.constraints.add(expr=sum(model.x[i,4] for i in row_indices) == data_csvfile.iloc[M,5])
model.constraints.add(expr=sum(model.x[i,5] for i in row_indices) == data_csvfile.iloc[M,6])
model.constraints.add(expr=sum(model.x[i,6] for i in row_indices) == data_csvfile.iloc[M,7])
model.constraints.add(expr=sum(model.x[i,7] for i in row_indices) == data_csvfile.iloc[M,8])


In [ ]:
model.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   16 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :   64 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)}
    x_index_0 : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
       

In [ ]:
!apt-get install -y -qq coinor-cbc

In [ ]:
opt_cbc = SolverFactory('cbc')

In [ ]:
result = opt_cbc.solve(model)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [ ]:
# solution display
print('\nObjective = ', model.objective())

print('\nDecision Variables with non zero values')
for i in row_indices:
  for j in col_indices:
    if model.x[i,j].value != 0 :
      print('Num of truck-loads of ACUs transported between ',data_csvfile['Warehouse'][i],' and ', data_csvfile.columns[j+1],':', model.x[i,j].value)
    else:
      pass


Objective =  635720.0

Decision Variables with non zero values
Num of truck-loads of ACUs transported between  Ahmedabad  and  Jodhpur : 100.0
Num of truck-loads of ACUs transported between  Bengaluru  and  Vellore : 50.0
Num of truck-loads of ACUs transported between  Bengaluru  and  Hyderabad : 200.0
Num of truck-loads of ACUs transported between  Chennai  and  Vellore : 200.0
Num of truck-loads of ACUs transported between  Delhi  and  Jodhpur : 70.0
Num of truck-loads of ACUs transported between  Delhi  and  Kanpur : 130.0
Num of truck-loads of ACUs transported between  kolkata  and  Patna : 80.0
Num of truck-loads of ACUs transported between  kolkata  and  Cuttack : 70.0
Num of truck-loads of ACUs transported between  lucknow  and  Kanpur : 70.0
Num of truck-loads of ACUs transported between  lucknow  and  Patna : 20.0
Num of truck-loads of ACUs transported between  Mumbai  and  Indore : 75.0
Num of truck-loads of ACUs transported between  Mumbai  and  Jodhpur : 130.0
Num of truck

7.ANSWER:\
Objective (Total Cost) =  635720.0

Decision Variables with non zero values \
Num of truck-loads of ACUs transported between  Ahmedabad  and  Jodhpur : 100.0 \
Num of truck-loads of ACUs transported between  Bengaluru  and  Vellore : 50.0 \
Num of truck-loads of ACUs transported between  Bengaluru  and  Hyderabad : 200.0 \
Num of truck-loads of ACUs transported between  Chennai  and  Vellore : 200.0 \
Num of truck-loads of ACUs transported between  Delhi  and  Jodhpur : 70.0 \
Num of truck-loads of ACUs transported between  Delhi  and  Kanpur : 130.0 \
Num of truck-loads of ACUs transported between  kolkata  and  Patna : 80.0 \
Num of truck-loads of ACUs transported between  kolkata  and  Cuttack : 70.0 \
Num of truck-loads of ACUs transported between  lucknow  and  Kanpur : 70.0 \
Num of truck-loads of ACUs transported between  lucknow  and  Patna : 20.0 \
Num of truck-loads of ACUs transported between  Mumbai  and  Indore : 75.0 \
Num of truck-loads of ACUs transported between  Mumbai  and  Jodhpur : 130.0 \
Num of truck-loads of ACUs transported between  Mumbai  and  Hyderabad : 50.0 \
Num of truck-loads of ACUs transported between  Nagpur  and  Hyderabad : 150.0 \
Num of truck-loads of ACUs transported between  Nagpur  and  Raipur : 50.0 

8.ANSWER:\
In case the Bengaluru-Patna link is disrupted and no transportation is possible on the
link. Without changing the pyomo model, here i have solved this problem simply by increasing the cost of Bangaluru-Patna link in the .csv file to a level which is greater than the cost of every link between Bangaluru and other markets.This will force the optimization problem to neglect Bangaluru-Patna link in order to achieve the minimum cost.

In [ ]:
data_csvfile = pd.read_csv('lab5_ex1_1.csv')

In [ ]:
#deactivate the old objective
model.objective.deactivate()

In [ ]:
model.new_objective = Objective(expr=sum(data_csvfile.iloc[i,j+1]*model.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

In [ ]:
model.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   16 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :   64 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)}
    x_index_0 : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
       

In [ ]:
!apt-get install -y -qq coinor-cbc

In [ ]:
opt_cbc = SolverFactory('cbc')

In [ ]:
new_result = opt_cbc.solve(model)
print('Solver status:', new_result.solver.status)
print('Solver termination condition:',new_result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [ ]:
# solution display
print('\nObjective = ', model.new_objective())

print('\nDecision Variables with non zero values')
for i in row_indices:
  for j in col_indices:
    if model.x[i,j].value != 0 :
      print('Num of truck-loads of ACUs transported between ',data_csvfile['Warehouse'][i],' and ', data_csvfile.columns[j+1],':', model.x[i,j].value)
    else:
      pass


Objective =  635720.0

Decision Variables with non zero values
Num of truck-loads of ACUs transported between  Ahmedabad  and  Jodhpur : 100.0
Num of truck-loads of ACUs transported between  Bengaluru  and  Vellore : 50.0
Num of truck-loads of ACUs transported between  Bengaluru  and  Hyderabad : 200.0
Num of truck-loads of ACUs transported between  Chennai  and  Vellore : 200.0
Num of truck-loads of ACUs transported between  Delhi  and  Jodhpur : 70.0
Num of truck-loads of ACUs transported between  Delhi  and  Kanpur : 130.0
Num of truck-loads of ACUs transported between  kolkata  and  Patna : 80.0
Num of truck-loads of ACUs transported between  kolkata  and  Cuttack : 70.0
Num of truck-loads of ACUs transported between  lucknow  and  Kanpur : 70.0
Num of truck-loads of ACUs transported between  lucknow  and  Patna : 20.0
Num of truck-loads of ACUs transported between  Mumbai  and  Indore : 75.0
Num of truck-loads of ACUs transported between  Mumbai  and  Jodhpur : 130.0
Num of truck

9.ANSWER:\
Objective (Total Cost) =  635720.0

Decision Variables with non zero values \
Num of truck-loads of ACUs transported between  Ahmedabad  and  Jodhpur : 100.0 \
Num of truck-loads of ACUs transported between  Bengaluru  and  Vellore : 50.0\
Num of truck-loads of ACUs transported between  Bengaluru  and  Hyderabad : 200.0\
Num of truck-loads of ACUs transported between  Chennai  and  Vellore : 200.0\
Num of truck-loads of ACUs transported between  Delhi  and  Jodhpur : 70.0\
Num of truck-loads of ACUs transported between  Delhi  and  Kanpur : 130.0\
Num of truck-loads of ACUs transported between  kolkata  and  Patna : 80.0\
Num of truck-loads of ACUs transported between  kolkata  and  Cuttack : 70.0\
Num of truck-loads of ACUs transported between  lucknow  and  Kanpur : 70.0\
Num of truck-loads of ACUs transported between  lucknow  and  Patna : 20.0\
Num of truck-loads of ACUs transported between  Mumbai  and  Indore : 75.0\
Num of truck-loads of ACUs transported between  Mumbai  and  Jodhpur : 130.0\
Num of truck-loads of ACUs transported between  Mumbai  and  Hyderabad : 50.0\
Num of truck-loads of ACUs transported between  Nagpur  and  Hyderabad : 150.0\
Num of truck-loads of ACUs transported between  Nagpur  and  Raipur : 50.0